#!/usr/bin/env bash
set -e

# ─────────────────────────────────────────────
#  SharedDrop — Local Network File Sharing
#  Install & Run Script
# ─────────────────────────────────────────────

REPO_URL="https://github.com/itssmfaisal/SharedDrop.git"
APP_DIR="$HOME/SharedDrop"
DEFAULT_PORT=3000

# ── Colors ────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

log()    { echo -e "${CYAN}[SharedDrop]${RESET} $*"; }
success(){ echo -e "${GREEN}[✔]${RESET} $*"; }
warn()   { echo -e "${YELLOW}[!]${RESET} $*"; }
error()  { echo -e "${RED}[✘]${RESET} $*"; exit 1; }

# ── Banner ────────────────────────────────────
echo -e "${BOLD}"
echo "  ███████╗██╗  ██╗ █████╗ ██████╗ ███████╗██████╗ ██████╗  ██████╗ ██████╗ "
echo "  ██╔════╝██║  ██║██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔═══██╗██╔══██╗"
echo "  ███████╗███████║███████║██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║██████╔╝"
echo "  ╚════██║██╔══██║██╔══██║██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║██╔═══╝ "
echo "  ███████║██║  ██║██║  ██║██║  ██║███████╗██████╔╝██████╔╝╚██████╔╝██║     "
echo "  ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝  ╚═════╝ ╚═╝     "
echo -e "${RESET}"
echo -e "  ${BOLD}Local Network File Sharing — by itssmfaisal${RESET}"
echo "  ─────────────────────────────────────────────"
echo ""

# ── Detect OS ─────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Linux*)  PLATFORM="linux" ;;
  Darwin*) PLATFORM="mac" ;;
  *)       error "Unsupported OS: $OS" ;;
esac
log "Detected platform: $PLATFORM"

# ── Check / Install Git ───────────────────────
if ! command -v git &>/dev/null; then
  warn "git not found. Installing..."
  if [ "$PLATFORM" = "linux" ]; then
    sudo apt-get update -qq && sudo apt-get install -y git
  elif [ "$PLATFORM" = "mac" ]; then
    xcode-select --install 2>/dev/null || true
  fi
fi
success "git is available"

# ── Check / Install Node.js (via nvm or system) ──
install_node() {
  warn "Node.js not found or version too old. Installing via nvm..."
  export NVM_DIR="$HOME/.nvm"
  if [ ! -d "$NVM_DIR" ]; then
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  fi
  # shellcheck source=/dev/null
  [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
  nvm install --lts
  nvm use --lts
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

if command -v node &>/dev/null; then
  NODE_VER=$(node -v | sed 's/v//' | cut -d. -f1)
  if [ "$NODE_VER" -lt 18 ]; then
    install_node
  else
    success "Node.js $(node -v) is available"
  fi
else
  install_node
  success "Node.js $(node -v) installed"
fi

# ── Check npm ─────────────────────────────────
if ! command -v npm &>/dev/null; then
  error "npm not found. Please install Node.js manually from https://nodejs.org"
fi
success "npm $(npm -v) is available"

# ── Clone or Update repo ───────────────────────
if [ -d "$APP_DIR/.git" ]; then
  log "SharedDrop already exists at $APP_DIR. Pulling latest changes..."
  git -C "$APP_DIR" pull --ff-only && success "Repository updated"
else
  log "Cloning SharedDrop into $APP_DIR..."
  git clone "$REPO_URL" "$APP_DIR"
  success "Repository cloned"
fi

cd "$APP_DIR"

# ── Install dependencies ───────────────────────
log "Installing dependencies..."
npm install --legacy-peer-deps
success "Dependencies installed"

# ── Build for production ───────────────────────
log "Building the Next.js app..."
npm run build
success "Build complete"

# ── Determine local IP ────────────────────────
get_local_ip() {
  if [ "$PLATFORM" = "mac" ]; then
    ipconfig getifaddr en0 2>/dev/null \
      || ipconfig getifaddr en1 2>/dev/null \
      || echo "127.0.0.1"
  else
    hostname -I 2>/dev/null | awk '{print $1}' \
      || ip route get 1 2>/dev/null | awk '{print $NF; exit}' \
      || echo "127.0.0.1"
  fi
}

LOCAL_IP=$(get_local_ip)
PORT="${SHAREDDROP_PORT:-$DEFAULT_PORT}"

# ── Write .env.local ──────────────────────────
cat > "$APP_DIR/.env.local" <<EOF
# Auto-generated by install.sh
HOSTNAME=0.0.0.0
PORT=$PORT
EOF

# ── PID / log file locations ──────────────────
PID_FILE="$APP_DIR/.shareddrop.pid"
LOG_FILE="$APP_DIR/.shareddrop.log"

# ── Stop any existing background instance ─────
stop_background() {
  if [ -f "$PID_FILE" ]; then
    OLD_PID=$(cat "$PID_FILE")
    if kill -0 "$OLD_PID" 2>/dev/null; then
      log "Stopping previous background instance (PID $OLD_PID)..."
      kill "$OLD_PID" 2>/dev/null && rm -f "$PID_FILE"
      success "Previous instance stopped"
    else
      rm -f "$PID_FILE"
    fi
  fi
}

# ── Detach: show summary and save PID ─────────
show_detached_message() {
  local pid="$1"
  echo "$pid" > "$PID_FILE"
  disown "$pid" 2>/dev/null || true
  echo ""
  echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo -e "  📦 ${BOLD}SharedDrop detached to background!${RESET}"
  echo -e ""
  echo -e "  Local:    ${CYAN}http://localhost:${PORT}${RESET}"
  echo -e "  Network:  ${CYAN}http://${LOCAL_IP}:${PORT}${RESET}"
  echo -e ""
  echo -e "  PID:      ${BOLD}$pid${RESET}"
  echo -e "  Logs:     ${BOLD}$LOG_FILE${RESET}"
  echo -e ""
  echo -e "  To view logs:  ${YELLOW}tail -f $LOG_FILE${RESET}"
  echo -e "  To stop:       ${YELLOW}kill \$(cat $PID_FILE)${RESET}"
  echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo ""
}

# ── Already running? Offer menu ───────────────
if [ -f "$PID_FILE" ]; then
  RUNNING_PID=$(cat "$PID_FILE")
  if kill -0 "$RUNNING_PID" 2>/dev/null; then
    echo ""
    echo -e "${YELLOW}[!]${RESET} SharedDrop is already running in the background (PID ${BOLD}$RUNNING_PID${RESET})"
    echo -e "    Local:   ${CYAN}http://localhost:${PORT}${RESET}"
    echo -e "    Network: ${CYAN}http://${LOCAL_IP}:${PORT}${RESET}"
    echo ""
    echo -e "  [${BOLD}R${RESET}] Restart   [${BOLD}S${RESET}] Stop   [${BOLD}Q${RESET}] Quit"
    echo ""

    old_term=$(stty -g </dev/tty 2>/dev/null)
    stty raw -echo </dev/tty 2>/dev/null
    key=$(dd bs=1 count=1 </dev/tty 2>/dev/null)
    stty "$old_term" </dev/tty 2>/dev/null
    echo ""

    case "${key,,}" in
      r)
        log "Restarting..."
        kill "$RUNNING_PID" 2>/dev/null; rm -f "$PID_FILE"; sleep 1
        ;;
      s)
        kill "$RUNNING_PID" 2>/dev/null; rm -f "$PID_FILE"
        success "SharedDrop stopped."; exit 0
        ;;
      *)
        log "Exiting without changes."; exit 0
        ;;
    esac
  else
    rm -f "$PID_FILE"
  fi
fi

stop_background

# ── Print running banner ───────────────────────
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "  🚀 ${BOLD}SharedDrop is running!${RESET}"
echo -e ""
echo -e "  Local:    ${CYAN}http://localhost:${PORT}${RESET}"
echo -e "  Network:  ${CYAN}http://${LOCAL_IP}:${PORT}${RESET}"
echo -e ""
echo -e "  Share the ${BOLD}Network${RESET} URL with devices on your Wi-Fi."
echo -e ""
echo -e "  Press ${BOLD}D${RESET} to detach (run in background)"
echo -e "  Press ${BOLD}Ctrl+C${RESET} to stop"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""

# ── Start the app.
#    stdin </dev/null — Node.js gets no terminal input at all.
#    stdout+stderr go to terminal so logs are visible.
HOST=0.0.0.0 PORT=$PORT npm start </dev/null &
APP_PID=$!

# Non-interactive (piped) shell — just wait forever
if [ ! -t 1 ]; then
  wait "$APP_PID"
  exit 0
fi

# ── Signal file: reader subprocess writes here when D is pressed ──
KEY_SIGNAL=$(mktemp /tmp/shareddrop_key.XXXXXX)

# ── Spawn dedicated key-reader subprocess.
#    It has exclusive ownership of /dev/tty in raw mode.
#    The app process has no stdin so there is ZERO competition.
(
  old_term=$(stty -g </dev/tty 2>/dev/null)
  stty raw -echo </dev/tty 2>/dev/null
  while true; do
    # blocking read — waits until exactly one byte arrives on /dev/tty
    ch=$(dd bs=1 count=1 </dev/tty 2>/dev/null)
    case "$ch" in
      d|D)
        printf 'd' > "$KEY_SIGNAL"
        break
        ;;
      # q/Q or Ctrl+C from tty → write 'q' so parent can exit cleanly
      q|Q|$'\x03')
        printf 'q' > "$KEY_SIGNAL"
        break
        ;;
    esac
  done
  stty "$old_term" </dev/tty 2>/dev/null
) &
READER_PID=$!

# ── Ctrl+C on the main process (SIGINT sent to whole group) ───────
trap '
  kill "$READER_PID" 2>/dev/null
  wait "$READER_PID" 2>/dev/null
  rm -f "$KEY_SIGNAL"
  echo ""
  log "Stopping SharedDrop..."
  kill "$APP_PID" 2>/dev/null
  wait "$APP_PID" 2>/dev/null
  echo ""
  success "SharedDrop stopped. Goodbye!"
  exit 0
' INT TERM

# ── Poll loop: checks signal file every 0.2 s.
#    The main shell is NOT blocked — it just sleeps briefly.
#    The reader subprocess handles all the blocking tty I/O.
action=""
while kill -0 "$APP_PID" 2>/dev/null; do
  if [ -s "$KEY_SIGNAL" ]; then
    action=$(cat "$KEY_SIGNAL")
    break
  fi
  sleep 0.2
done

# Disarm trap and clean up reader
trap - INT TERM
kill "$READER_PID" 2>/dev/null
wait "$READER_PID" 2>/dev/null
rm -f "$KEY_SIGNAL"

case "$action" in
  d)
    # Kill the foreground app and relaunch with nohup so it
    # survives terminal close and writes logs to file
    log "Detaching..."
    kill "$APP_PID" 2>/dev/null
    wait "$APP_PID" 2>/dev/null
    sleep 0.3
    nohup bash -c "HOST=0.0.0.0 PORT=$PORT npm --prefix '$APP_DIR' start" \
      > "$LOG_FILE" 2>&1 &
    BG_PID=$!
    show_detached_message "$BG_PID"
    ;;
  q)
    log "Stopping SharedDrop..."
    kill "$APP_PID" 2>/dev/null
    wait "$APP_PID" 2>/dev/null
    success "SharedDrop stopped. Goodbye!"
    exit 0
    ;;
  *)
    # App exited on its own
    warn "SharedDrop exited unexpectedly."
    exit 1
    ;;
esac
