#!/usr/bin/env bash
set -e

# ─────────────────────────────────────────────
#  SharedDrop — Local Network File Sharing
#  Install & Run Script
# ─────────────────────────────────────────────

REPO_URL="https://github.com/itssmfaisal/SharedDrop.git"
APP_DIR="$HOME/SharedDrop"
DEFAULT_PORT=3000

# ── Colors ────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

log()    { echo -e "${CYAN}[SharedDrop]${RESET} $*"; }
success(){ echo -e "${GREEN}[✔]${RESET} $*"; }
warn()   { echo -e "${YELLOW}[!]${RESET} $*"; }
error()  { echo -e "${RED}[✘]${RESET} $*"; exit 1; }

# ── Banner ────────────────────────────────────
echo -e "${BOLD}"
echo "  ███████╗██╗  ██╗ █████╗ ██████╗ ███████╗██████╗ ██████╗  ██████╗ ██████╗ "
echo "  ██╔════╝██║  ██║██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔═══██╗██╔══██╗"
echo "  ███████╗███████║███████║██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║██████╔╝"
echo "  ╚════██║██╔══██║██╔══██║██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║██╔═══╝ "
echo "  ███████║██║  ██║██║  ██║██║  ██║███████╗██████╔╝██████╔╝╚██████╔╝██║     "
echo "  ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝  ╚═════╝ ╚═╝     "
echo -e "${RESET}"
echo -e "  ${BOLD}Local Network File Sharing — by itssmfaisal${RESET}"
echo "  ─────────────────────────────────────────────"
echo ""

# ── Detect OS ─────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Linux*)  PLATFORM="linux" ;;
  Darwin*) PLATFORM="mac" ;;
  *)       error "Unsupported OS: $OS" ;;
esac
log "Detected platform: $PLATFORM"

# ── Check / Install Git ───────────────────────
if ! command -v git &>/dev/null; then
  warn "git not found. Installing..."
  if [ "$PLATFORM" = "linux" ]; then
    sudo apt-get update -qq && sudo apt-get install -y git
  elif [ "$PLATFORM" = "mac" ]; then
    xcode-select --install 2>/dev/null || true
  fi
fi
success "git is available"

# ── Check / Install Node.js (via nvm or system) ──
install_node() {
  warn "Node.js not found or version too old. Installing via nvm..."
  export NVM_DIR="$HOME/.nvm"
  if [ ! -d "$NVM_DIR" ]; then
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  fi
  # shellcheck source=/dev/null
  [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
  nvm install --lts
  nvm use --lts
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

if command -v node &>/dev/null; then
  NODE_VER=$(node -v | sed 's/v//' | cut -d. -f1)
  if [ "$NODE_VER" -lt 18 ]; then
    install_node
  else
    success "Node.js $(node -v) is available"
  fi
else
  install_node
  success "Node.js $(node -v) installed"
fi

# ── Check npm ─────────────────────────────────
if ! command -v npm &>/dev/null; then
  error "npm not found. Please install Node.js manually from https://nodejs.org"
fi
success "npm $(npm -v) is available"

# ── Clone or Update repo ───────────────────────
if [ -d "$APP_DIR/.git" ]; then
  log "SharedDrop already exists at $APP_DIR. Pulling latest changes..."
  git -C "$APP_DIR" pull --ff-only && success "Repository updated"
else
  log "Cloning SharedDrop into $APP_DIR..."
  git clone "$REPO_URL" "$APP_DIR"
  success "Repository cloned"
fi

cd "$APP_DIR"

# ── Install dependencies ───────────────────────
log "Installing dependencies..."
npm install --legacy-peer-deps
success "Dependencies installed"

# ── Build for production ───────────────────────
log "Building the Next.js app..."
npm run build
success "Build complete"

# ── Determine local IP ────────────────────────
get_local_ip() {
  if [ "$PLATFORM" = "mac" ]; then
    ipconfig getifaddr en0 2>/dev/null \
      || ipconfig getifaddr en1 2>/dev/null \
      || echo "127.0.0.1"
  else
    hostname -I 2>/dev/null | awk '{print $1}' \
      || ip route get 1 2>/dev/null | awk '{print $NF; exit}' \
      || echo "127.0.0.1"
  fi
}

LOCAL_IP=$(get_local_ip)
PORT="${SHAREDDROP_PORT:-$DEFAULT_PORT}"

# ── Write .env.local ──────────────────────────
cat > "$APP_DIR/.env.local" <<EOF
# Auto-generated by install.sh
HOSTNAME=0.0.0.0
PORT=$PORT
EOF

# ── PID file location ─────────────────────────
PID_FILE="$APP_DIR/.shareddrop.pid"
LOG_FILE="$APP_DIR/.shareddrop.log"

# ── Stop any existing background instance ─────
stop_background() {
  if [ -f "$PID_FILE" ]; then
    OLD_PID=$(cat "$PID_FILE")
    if kill -0 "$OLD_PID" 2>/dev/null; then
      log "Stopping previous background instance (PID $OLD_PID)..."
      kill "$OLD_PID" && rm -f "$PID_FILE"
      success "Previous instance stopped"
    else
      rm -f "$PID_FILE"
    fi
  fi
}

# ── Launch in foreground ───────────────────────
launch_foreground() {
  echo ""
  echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo -e "  🚀 ${BOLD}SharedDrop is running!${RESET}"
  echo -e ""
  echo -e "  Local:    ${CYAN}http://localhost:${PORT}${RESET}"
  echo -e "  Network:  ${CYAN}http://${LOCAL_IP}:${PORT}${RESET}"
  echo -e ""
  echo -e "  Share the ${BOLD}Network${RESET} URL with devices on your Wi-Fi."
  echo -e ""
  echo -e "  Press ${BOLD}D${RESET} to detach (run in background)"
  echo -e "  Press ${BOLD}Ctrl+C${RESET} to stop"
  echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo ""

  # ── Key fix: redirect app stdin from /dev/null so it never
  #    competes for keystrokes. Output still flows to terminal.
  HOST=0.0.0.0 PORT=$PORT npm start </dev/null &
  APP_PID=$!

  # Non-interactive shell (e.g. curl | bash) — just wait
  if [ ! -t 1 ]; then
    wait "$APP_PID"
    exit 0
  fi

  # ── Read keypresses from /dev/tty (the real terminal),
  #    not stdin, so app output doesn't interfere.
  detached=false
  old_tty=$(stty -g </dev/tty 2>/dev/null)

  # Trap Ctrl+C so we can clean up gracefully
  trap '
    stty "$old_tty" </dev/tty 2>/dev/null
    echo ""
    log "Stopping SharedDrop..."
    kill "$APP_PID" 2>/dev/null
    wait "$APP_PID" 2>/dev/null
    echo ""
    success "SharedDrop stopped. Goodbye!"
    exit 0
  ' INT TERM

  stty raw -echo </dev/tty 2>/dev/null

  while kill -0 "$APP_PID" 2>/dev/null; do
    # Read exactly one char from the real terminal (0.3s timeout)
    key=$(dd bs=1 count=1 </dev/tty 2>/dev/null)
    case "$key" in
      d|D)
        stty "$old_tty" </dev/tty 2>/dev/null
        trap - INT TERM
        detached=true
        break
        ;;
    esac
  done

  stty "$old_tty" </dev/tty 2>/dev/null
  trap - INT TERM

  if [ "$detached" = true ]; then
    detach_to_background "$APP_PID"
  fi
}

# ── Detach running process to background ──────
detach_to_background() {
  local pid="${1:-}"

  if [ -z "$pid" ]; then
    # Fresh background launch (called directly)
    stop_background
    HOST=0.0.0.0 PORT=$PORT nohup npm start > "$LOG_FILE" 2>&1 &
    pid=$!
  fi

  echo "$pid" > "$PID_FILE"
  disown "$pid" 2>/dev/null || true

  echo ""
  echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo -e "  📦 ${BOLD}SharedDrop detached to background!${RESET}"
  echo -e ""
  echo -e "  Local:    ${CYAN}http://localhost:${PORT}${RESET}"
  echo -e "  Network:  ${CYAN}http://${LOCAL_IP}:${PORT}${RESET}"
  echo -e ""
  echo -e "  PID:      ${BOLD}$pid${RESET}"
  echo -e "  Logs:     ${BOLD}$LOG_FILE${RESET}"
  echo -e ""
  echo -e "  To view logs:  ${YELLOW}tail -f $LOG_FILE${RESET}"
  echo -e "  To stop:       ${YELLOW}kill \$(cat $PID_FILE)${RESET}"
  echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo ""
}

# ── Check if already running in background ────
if [ -f "$PID_FILE" ]; then
  RUNNING_PID=$(cat "$PID_FILE")
  if kill -0 "$RUNNING_PID" 2>/dev/null; then
    echo ""
    echo -e "${YELLOW}[!]${RESET} SharedDrop is already running in the background (PID ${BOLD}$RUNNING_PID${RESET})"
    echo -e "    Local:   ${CYAN}http://localhost:${PORT}${RESET}"
    echo -e "    Network: ${CYAN}http://${LOCAL_IP}:${PORT}${RESET}"
    echo ""
    echo -e "  What would you like to do?"
    echo -e "  [${BOLD}R${RESET}] Restart   [${BOLD}S${RESET}] Stop   [${BOLD}Q${RESET}] Quit"
    echo ""

    if [ -t 1 ]; then
      old_tty=$(stty -g </dev/tty 2>/dev/null)
      stty raw -echo </dev/tty 2>/dev/null
      key=$(dd bs=1 count=1 </dev/tty 2>/dev/null)
      stty "$old_tty" </dev/tty 2>/dev/null
      echo ""

      case "${key,,}" in
        r)
          log "Restarting..."
          kill "$RUNNING_PID" 2>/dev/null
          rm -f "$PID_FILE"
          sleep 1
          ;;
        s)
          kill "$RUNNING_PID" 2>/dev/null
          rm -f "$PID_FILE"
          success "SharedDrop stopped."
          exit 0
          ;;
        *)
          log "Exiting without changes."
          exit 0
          ;;
      esac
    else
      exit 0
    fi
  else
    rm -f "$PID_FILE"
  fi
fi

# ── Main: Launch ──────────────────────────────
stop_background
launch_foreground